# Generated by Django 4.2.13 on 2024-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_airplane_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
